export { default as Navigation } from './Navigation'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Portfolio } from './Portfolio'
export { default as Footer } from './Footer'
